image: node:10

test:
  stage: test
  script:
    - CI=true yarn test || true

pages:
  cache:
    paths:
    - node_modules/
 
  stage: deploy
  script:
  - yarn install
  - yarn build
  - rm -rf public
  - mv build public
  artifacts:
    paths:
    - public # mandatory, other folder won't work
  only:
  - master # or dev, the branch you want to publish