// Dynamically generated by I18nextPreWebpackPlugin, please do not touch.
// If you want to add or remove a language, simply change languages array in i18next-parser config file,
// then run `yarn build:translations-parse` to create translations tree and,
// if you want auto-translation, run `yarn build:auto-translate`

import en from './locales/en/translation.json';
import it from './locales/it/translation.json';
import es from './locales/es/translation.json';
import fr from './locales/fr/translation.json';
import de from './locales/de/translation.json';
import zh from './locales/zh/translation.json';
import ar from './locales/ar/translation.json';

// the translations
export default {
  en: { translation: en },
  it: { translation: it },
  es: { translation: es },
  fr: { translation: fr },
  de: { translation: de },
  zh: { translation: zh },
  ar: { translation: ar },
};
